### ISSUE TITLE
How does the merge queue work?

### ISSUE THREAD

**Issue by eva-cosma** [UPB-CS-OpenSourceUpstream/tockloader-rs#14]
I have attempted to play around with github's new merge queue system, but I must say I am confused as to how it should function. Here's what I attempted to do, and what the outcomes were.

# Configuration
First, I've created a new branch named `queue-test` and created a new rule to enable the merge queue. Here is the (default) configuration.
![image](https://user-images.githubusercontent.com/20498967/236877237-7abd0d00-036c-4987-a163-f86c3d8ca5f1.png)

# First attempt
At first, the state of `queue-test` was that of the `main` branch, aka no CI ruleset implemented. When I created pull request #10 with a failing test, it did not show up any CI issues. This was as expected as neither that branch, nor the `queue-test` branch had any CI actions defined.

Afterwards, I created and merged PR #11 which (_should_) enable the CI actions to be enabled in the merge queue.
I have then merged PR #10, and it had merged with no issues. 
![image](https://user-images.githubusercontent.com/20498967/236878093-2f67817e-241e-4434-a8dd-638a476e79fd.png)
Note the presence of only 1 button after the merge happened. This will be relevant later

# Second attempt
I decided to revert PR #10, thus creating PR #12. This required me to make the push to the merge queue, and it succeeded, as expected.
![image](https://user-images.githubusercontent.com/20498967/236878387-e64d18d9-456e-40e7-ace0-cf5172222a4e.png)

Note the fact this has two buttons. When clicking `view details` I get informed that all tests passed.
![image](https://user-images.githubusercontent.com/20498967/236879185-a7c21a29-5be9-42e8-90a5-2f13bf0158fa.png)

My hypothesis was because PR #10 did not have the same (or any) CI actions as those in the target branch, the checks were getting skipped. As such, I created a new branch in my own fork which had as base `queue-test`. I then created PR #13 and merged it.
The PR was in the merge queue for a handful of seconds, and was pushed almost immediately, even though PR #13 failed all checks.
 
![image](https://user-images.githubusercontent.com/20498967/236879653-81632561-8f3e-4cd7-96da-b7bbd80abdcc.png)

While almost certainly no PR with a failing CI test would get put into the merge queue manually, why wouldn't the merge queue refuse to merge? 
Is this intended behavior, or am I missing something?

**Comment by alexandruradovici** [comment]
We had similar issues with merge queue, they are still in  beta 😄 . We have to enable *require status checks* to actually make the merge queue to run something.
<img width="763" alt="Screenshot 2023-05-09 at 11 19 06" src="https://user-images.githubusercontent.com/2838177/237037633-1b4d5a31-214f-4cb1-a9b6-f6bbd52dbe65.png">

**Comment by eva-cosma** [comment]
Oh wow! I did not expect it to be part of a different setting altogether, though I guess in hindsight it does make sense 😅. Thank you!

After enabling this options, things seem to be working as expected. Now the PRs in the merge queue are properly checked.

 Here are the checks for PR #15 :
![image](https://github.com/UPB-CS-OpenSourceUpstream/tockloader-rs/assets/20498967/3b77672c-0b5d-423d-8ef7-0a601f9b690d)
![image](https://github.com/UPB-CS-OpenSourceUpstream/tockloader-rs/assets/20498967/9433b781-e6db-44f6-b59d-644670559698)
